console.log("----- Arithmetic Operators -----");
var a = 10;
var b = 20;
console.log("Sum:", a + b);
console.log("Difference:", a - b);
console.log("Product:", a * b);
console.log("Quotient:", b / a);
console.log("Modulus:", b % a);
console.log("----------------");
console.log("----- Comparison Operators -----");
console.log("Equal:", a == b);
console.log("Not Equal:", a != b);
console.log("Greater Than:", a > b);
console.log("Less Than:", a < b);
console.log("Greater Than or Equal To:", a >= b);
console.log("Less Than or Equal To:", a <= b);
console.log("----------------");
console.log("----- Logical Operators -----");
var x = true;
var y = false;
console.log("AND (x && y):", x && y);
console.log("OR (x || y):", x || y);
console.log("NOT (!x):", !x);
console.log("----------------");
console.log("----- Assignment Operators -----");
var c = 10;
var d = 5;
console.log(c += d);
console.log(c -= d);
console.log(c *= d);
console.log(c /= d);
console.log(c %= d);
console.log("----------------");
